#!/bin/sh
if [ -f "/etc/config/netspeedtest" ]; then
    rm -f /etc/config/netspeedtest
fi

touch /etc/config/netspeedtest
uci -q batch <<-EOF >/dev/null
    set netspeedtest.config=netspeedtest
    commit netspeedtest
EOF